Feature/visitorCount
themoment-team/EveryGSM-server pull request #10
Opened 2023-06-05 08:15 UTC by Junho-06

# 작업내용 👀

> 방문자수 api 제작하였습니다

2023-06-06 00:41 UTC, jangwooooo requested changes
수고하셨습니다

2023-06-06 00:41 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/domain/project/service/ProjectService.java
> +        project.setVisitorCount(project.getVisitorCount() + 1);
여기도 `setter`사용보다는 따로 update메서드를 만드는 방법이 어떨까요?

2023-06-06 02:26 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/project/service/ProjectService.java
> +        project.setVisitorCount(project.getVisitorCount() + 1);
업데이트 메소드 만들고 사용하도록 변경하였습니다

2023-06-06 02:27 UTC, jangwooooo approved these changes

2023-06-06 04:29 UTC, hajeu approved these changes

2023-06-06 04:44 UTC, merged

2023-06-07 07:16 UTC, jyeonjyan-flo commented on src/main/resources/application.yml
> -      ddl-auto: create-drop
이거 profile 별로 관리하시는거죠 ~?
운영 경험상 prod ddl 설정은 off 하시는게 좋을 것 같아요.

2023-06-07 07:16 UTC, jyeonjyan-flo commented on src/main/java/com/themoment/everygsm/domain/project/service/ProjectService.java
> +        project.updateVisitor(project.getVisitorCount() + 1);
방문자 hit 경우에는 다른 API에 비해서 비교적 많은 traffic이 몰리는 API로 예상되는데요.
이 부분은 lock 같은걸로 해결한다면 FE 쪽에서 side-effect(landing latency 등)가 있을 수 있어서 논의가 필요해보입니다. 
결론은 임시로 이렇게 처리하고 넘어가도 크리티컬한건 없지만, 아무튼 제대로된 집게는 안될거다입니다.

2023-06-07 17:02 UTC, Junho-06 commented on src/main/resources/application.yml
> -      ddl-auto: create-drop
profile 별로 관리할수 있도록 바꾸었고 prod 환경은 ddl 설정을 off하였습니다