Feature/user
themoment-team/EveryGSM-server pull request #3
Opened 2023-05-23 07:40 UTC by Junho-06

# 작업내용 👀

> 유저 기능을 구현하였습니다

2023-05-23 11:09 UTC, yebin0310 commented on src/main/java/com/themoment/everygsm/domain/user/service/UserService.java
> +            throw new CustomException("패스워드가 틀렸습니다", HttpStatus.BAD_REQUEST);
위와 똑같이 `비밀번호` 로 통일하는게 좋을 것 같네요 !

2023-05-23 11:15 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/user/service/UserService.java
> +            throw new CustomException("패스워드가 틀렸습니다", HttpStatus.BAD_REQUEST);
수정하였습니다

2023-05-25 08:18 UTC, hajeu commented on src/main/java/com/themoment/everygsm/domain/user/controller/UserController.java
> +    public ResponseEntity<Void> signUp(@RequestBody @Valid SignUpRequestDto signUpRequestDto, HttpServletRequest request) {
request 매개변수는 사용하지 않는건가요?

2023-05-25 08:18 UTC, hajeu commented on src/main/java/com/themoment/everygsm/domain/user/dto/response/TokenResponse.java
> +public class TokenResponse {
사용하지 않는 클래스로 보이는데 삭제하는게 좋을것 같습니다.

2023-05-25 08:18 UTC, hajeu commented on src/main/java/com/themoment/everygsm/domain/user/dto/response/NewTokenResponse.java
> +public class NewTokenResponse {
SignInResponseDto 클래스랑 코드가 중복되는데 TokenResponse 클래스로 통일하는게 좋을것 같아요.

2023-05-25 08:23 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/user/controller/UserController.java
> +    public ResponseEntity<Void> signUp(@RequestBody @Valid SignUpRequestDto signUpRequestDto, HttpServletRequest request) {
[이 커밋](https://github.com/themoment-team/EveryGSM-server/pull/3/commits/d53898131f212857196a2d80ea6412cae18fc37b)에서 사용하지 않는것 같아서 삭제하였습니다.

2023-05-25 08:25 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/user/dto/response/TokenResponse.java
> +public class TokenResponse {
반영하였습니다!

2023-05-25 08:35 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/user/dto/response/NewTokenResponse.java
> +public class NewTokenResponse {
반영하였습니다!

2023-05-26 03:10 UTC, jangwooooo requested changes
수고하셨습니다 !!

2023-05-26 03:10 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/global/filter/JwtRequestFilter.java
> +
log를 찍는 부분은 없는 것으로 보여지는데요.
사용하지 않는다면 제거하는게 좋을 것 같습니다.

2023-05-26 03:10 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/global/security/SecurityConfig.java
> +
결국은  `/auth/**`만 있어도 되는 거 같습니다.

2023-05-26 03:10 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/global/util/UserUtil.java
> +
여기도 log를 찍는 부분은 없는 거 같은데요.
사용하지 않는다면 제거하는게 좋을 것 같습니다.

2023-05-26 03:10 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/global/util/UserUtil.java
> +    }
어떤 email로 request를 해서 발생한 Exception인지 알아차리기 위해 detailMessage에 email을 같이 담으면 좋을 것 같습니다.

2023-05-27 05:54 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/global/filter/JwtRequestFilter.java
> +
삭제하였습니다!

2023-05-27 05:54 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/global/security/SecurityConfig.java
> +
수정하였습니다!

2023-05-27 05:54 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/global/util/UserUtil.java
> +
제거하였습니다!

2023-05-27 05:55 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/global/util/UserUtil.java
> +    }
추가하였습니다

2023-05-27 06:07 UTC, jangwooooo approved these changes

2023-05-27 06:10 UTC, hajeu approved these changes

2023-05-27 06:18 UTC, merged