Feature/lookupFilter
themoment-team/EveryGSM-server pull request #6
Opened 2023-05-30 01:56 UTC by Junho-06

# 작업내용 👀

> 하트, 등록시간 순 오름차순 내림차순 정렬을 구현하였습니다!

2023-06-01 02:25 UTC, jangwooooo requested changes
수고하셨습니다

2023-06-01 02:25 UTC, jangwooooo commented on src/main/java/com/themoment/everygsm/domain/heart/service/HeartService.java
> +        projectRepository.save(project);
`projectRepository.save(project);` 이렇게 직접 save를 하지 않아도 `Dirty Checking`에 의해 변경사항이 자동으로 db에 반영되는 거로 알고 있습니다.
save하는 구문이 필요한지 검토부탁드립니다.

- [참고 링크](https://jojoldu.tistory.com/415)

2023-06-02 02:00 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/heart/service/HeartService.java
> +        projectRepository.save(project);
수정하였습니다, 추가적으로 엔티티 필드가 많아서 @DynamicUpdate 를 통해 HeartCount필드만 업데이트하도록 하였습니다.

2023-06-02 10:12 UTC, jangwooooo approved these changes

2023-06-02 10:24 UTC, hajeu approved these changes

2023-06-02 11:43 UTC, merged

2023-06-07 07:11 UTC, jyeonjyan-flo commented on src/main/java/com/themoment/everygsm/domain/project/controller/ProjectSortController.java
> +    }
어차피 base는 똑같은 API라고 생각듭니다.
API 구성을 `/heart/sort?strategy=asc` 처럼 `strategy` 라는 동적 requestParam을 두어 분기 처리하는것이 좋아보입니다.

아래 이어지는 `/created/**` API에도 적용되는 리뷰입니다.

2023-06-07 07:11 UTC, jyeonjyan-flo commented on src/main/java/com/themoment/everygsm/domain/project/service/ProjectSortService.java
> +    @Transactional(rollbackFor = Exception.class)
이런게 습관이 되어버리면 안됩니다.
rollback을 하면 안되는 상황에서도 하게 되니.. 
spring fw가 default, 즉 fw가 의도함을 정확히 이해하시고 사용하시길 바래요.

2023-06-07 07:11 UTC, jyeonjyan-flo commented on src/main/java/com/themoment/everygsm/domain/heart/service/HeartService.java
> +        }
아까 이쪽 리뷰했던거 같은데.. 개인적으로 `throw new Exception`은 과한 처리라고 보고있습니다.
`log.warn()` 정도로 찍고 넘어가는것도 좋을 것 같습니다.

2023-06-07 16:06 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/project/controller/ProjectSortController.java
> +    }
정렬 서비스를 requestParam에 따라 처리하도록 하였습니다 ( Created 기준 정렬도 똑같이 바꿧습니다! )
```java
//controller
@GetMapping("/heart")
    public ResponseEntity<List<ProjectResponseDto>> getSortedProjectsByHeart(@RequestParam String strategy) {
        return new ResponseEntity<>(projectSortService.sortProjectsByHeart(strategy), HttpStatus.OK);
    }

// service
public List<ProjectResponseDto> sortProjectsByHeart(String strategy) {
        return switch (strategy) {
            case "asc" -> projectRepository.findAllByOrderByHeartCountAsc().stream()
                    .map(ProjectResponseDto::from)
                    .toList();
            case "desc" -> projectRepository.findAllByOrderByHeartCountDesc().stream()
                    .map(ProjectResponseDto::from)
                    .toList();
            default -> throw new CustomException("잘못된 정렬방식 입니다.", HttpStatus.BAD_REQUEST);
        };
        ```

2023-06-07 16:45 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/project/service/ProjectSortService.java
> +    @Transactional(rollbackFor = Exception.class)
넵 앞으로는 사용하는 기술에 대해 이해하고 사용할 수 있도록 하겠습니다..

2023-06-07 16:49 UTC, Junho-06 commented on src/main/java/com/themoment/everygsm/domain/heart/service/HeartService.java
> +        }
넵 생각해보니 과한 측면도 있는것 같아 코드 수정하였습니다